move deps in root cargo.toml
thrumdev/blobs pull request #195
Opened 2024-01-16 17:20 UTC by gabriele-0201

closes #134

2024-01-16 17:20 UTC, gabriele-0201 commented
Current dependencies on/for this PR:
* `main`
  * **PR #195** <a href="https://app.graphite.dev/github/pr/thrumdev/blobs/195?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thrumdev/blobs/195?utm_source=stack-comment).

2024-01-19 00:46 UTC, rphmeier commented
@pepyakin can you review this one? The changes look like they'd work, to me, but does it accomplish what you wanted it to?

2024-01-24 10:56 UTC, pepyakin requested changes
Yes, this is exactly what I meant.

2024-01-24 10:56 UTC, pepyakin commented on Cargo.toml
> +authors = ["Robert Habermeier - @rphmeier" , "Sergei Shulepov - @pepyakin", "Gabriele Miotti - @gabriele-0201"]
A couple of things. I think this field is conventionally has the same format as name and email.

Quote from Cargo docs:

```
[package]
# ...
authors = ["Graydon Hoare", "Fnu Lnu <no-reply@rust-lang.org>"]
```

However, I would rather not put any names here. It's just not scalable, may introduce some unnecessary feelings, and most importantly serves no purpose! 

I see the following ways:

1. remove it altogether. I don't think it's required.
2. use unpersonified email, similar to what we do in Parity. smth like `parity developers <admin@parity.io>`.

2024-01-24 18:49 UTC, pepyakin approved these changes

2024-01-24 18:49 UTC, merged