ci: print log on test failure and clean cache
thrumdev/blobs pull request #262
Opened 2024-02-27 19:12 UTC by gabriele-0201

2024-02-27 19:12 UTC, gabriele-0201 commented
Current dependencies on/for this PR:
* **#251** <a href="https://app.graphite.dev/github/pr/thrumdev/blobs/251?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#262** <a href="https://app.graphite.dev/github/pr/thrumdev/blobs/262?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/thrumdev/blobs/262?utm_source=stack-comment).

2024-02-28 04:22 UTC, rphmeier approved these changes
Does cleaning the cargo cache not cause a complete rebuild from scratch?

Our CI times will go through the roof unless I misunderstand. Though it seems unavoidable without setting up something like `sccache`.

2024-02-28 09:00 UTC, pepyakin requested changes
I understand the potential benefit of it in case of a normal GHA. There, each runner starts without any state and will have to download, uncompress the cache. Whenever it is done with it, it will update the cache, compress it and upload. Reducing the cache size and storing only necessary things that are slow to download or rebuild can indeed improve the CI performance.

It doesn't apply to our situation: we do not rely on the GHA provided machines and we are using our own. As such, we have plenty of cache which is available immediatelly.

What am I missing?

2024-02-29 08:24 UTC, pepyakin commented
Ok, this is a bit more clear, however I am still not convinced in that it's a good solution. Specifically, I don't understand exactly the reason of failure and how usage of `cargo cache` mends it.

TBH, I have a suspicion that you are on the wrong path. My reasoning is based on the following:

1. cargo home mainly stores binaries by `cargo install` and `rustup` and sources from crates.io and git.
2. it's not clear how you came to conclusion that you got the wrong binary exactly. However, I assume that you ran it using `cargo run`, not `cargo install`. Therefore, the `$CARGO_HOME/bin` shouldn't help.
3. `ikura-shim` is also not a git/crates.io dependency, so cleaning the source parts of the cargo cache should not help either.

So it doesn't look like this is the root cause. Maybe, removing those caches somehow invalidates the build and triggers rebuilding, or something along those lines? 

> I aim to understand where the local workspace stores incremental build data and how it influences binary recompilation (deleting items from git checkouts may not provide any benefits)

it shouldn't really matter whether it's local workspace or anything else, or incremental or not, the compiled artifacts are stored under `CARGO_TARGET`, which is configured to be `/cargo_target` on the runner.

2024-02-29 09:58 UTC, gabriele-0201 commented
> however I am still not convinced in that it's a good solution

I agree, initially I thought `cargo-cache` was doing something different.

> removing those caches somehow invalidates the build and triggers rebuilding, or something along those lines?

Yes, probably that's what happens. Yesterday, it worked only by chance. On the second push, it stopped working.

I will close this PR, fix the last things for #251, and then go back to this problem

2024-02-29 09:58 UTC, closed without merging